### ISSUE TITLE
Add GitHub URL to meshcommander npm package

### ISSUE THREAD

**Issue by rgl** [Ylianst/MeshCommander#1]
It would be nice to have a link to this GitHub repository at https://www.npmjs.com/package/meshcommander

For doing this just follow https://docs.npmjs.com/files/package.json#repository

Oh, looking at the package.json file, it seems to be an nw app, which means the npm package does not comes from this repository at all?

**Comment by Ylianst** [comment]
Good ask. Just fixed it.

**Comment by rgl** [comment]
I can see the npm page now has the github url and that is super nice! :-)

Though, in https://github.com/Ylianst/MeshCommander/commit/fed5e5a70bd001decb88051b7c25ca5a91830c2b you mention that you are updating package.json, but the commit has no changes in that file. Did you forget to commit anything else?
