### ISSUE TITLE
KVM no longer working with v0.8.3

### ISSUE THREAD

**Issue by bthebaudeau** [Ylianst/MeshCommander#11]
With my setup, KVM ("Remote Desktop" section) works fine with v0.8.2, but not with v0.8.3. After clicking "Connect", the state switches to "Setup..." for a couple of seconds, then to "Disconnected".

AMT host: Lenovo ThinkServer TS140, BIOS version: FBKTD9AUS, Intel ME v9.1.45 activated in Admin Control Mode (ACM), no OS, machine reset to BIOS.
Client: Windows 10 Pro 1909, 64-bit, fully updated, RLE8.

**Comment by bthebaudeau** [comment]
MeshCommander was installed using the MSI installer.

Tell me if you need more information.

**Comment by Ylianst** [comment]
Thanks for the report. I just fixed it, you can re-download v0.8.3 now, it includes the fix. I will publish v0.8.4 in a few minutes.

**Comment by Ylianst** [comment]
Just published MeshCommander v0.8.4.

**Comment by bthebaudeau** [comment]
I confirm that this issue no longer exists in v0.8.4. Thanks.
