### ISSUE TITLE
KVM shows black screen on HP EliteBook 850 G6

### ISSUE THREAD

**Issue by Armchairplum** [Ylianst/MeshCommander#13]
When using it to remote the device, one can see that it is connected and Keyboard/Mouse input is passed through.
No image is fed back into the client.
![MeshCommander](https://user-images.githubusercontent.com/25501729/83596584-19e21080-a5b9-11ea-9bba-f502fabc9daa.png)

When using VNC Viewer Plus, the screen is captured and sent to the client.
![VNC Viewer](https://user-images.githubusercontent.com/25501729/83596603-24040f00-a5b9-11ea-8df7-3289dc243ce8.png)

CPU Intel i5-8365U
Bios R70 Ver. 01.03.04
Intel ME v12.0.45 activated in Admin Control Mode (ACM)

MeshCommander 0.8.4 - MSI version is in use.

**Comment by Ylianst** [comment]
I fixed this. I did not change the version number yet, but uninstall, [download](https://www.meshcommander.com/meshcommander) and re-install v0.8.4 and let me know if it works.

**Comment by Armchairplum** [comment]
Thanks for that Ylianst, confirmed that you've done the trick!
This would have been super handy when NZ first went into lockdown!
Keep it up!
