### ISSUE TITLE
MeshCommander 0.8.4 - SOL stops working after change 80x25 to 100x30

### ISSUE THREAD

**Issue by NotCommonUser** [Ylianst/MeshCommander#14]
Hi.
Following scenario:
1. Connect
2. Connect SOL
3. all works ok
4. change 80x25 to 100x30
5. Only Enter works. None of other keys are sent to the other side.

To get SOL back to working condition SOL needs to be disconnected and re-connected again.

Tested on: NUC7i5DNHE DNKBLi5v.86A.0068.2020.0312.1721  IME v11.8.70

**Comment by Ylianst** [comment]
Published a new MeshCommander v0.8.4, not sure what edition you are using but latest published should fix it. If using .MSI version, you need to uninstall, download, re-install.

**Comment by NotCommonUser** [comment]
Works properly now.
Thank you *very* much!
