### ISSUE TITLE
Attempts to load MeshCommander into Intel AMT via Firmware Loader and MeshCMD result in error message

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCommander#22]
Hi @Ylianst, I finally got around to trying out MeshCommander's Intel AMT integration with my Intel NUC earlier today but I've been running into some issues that I haven't been able to solve yet.

**NUC Model:** NUC7i7DNHE
**BIOS:** Intel Corp.DNKBLi7v.86A.0069.2020.0610.1805 (latest)
**Intel AMT Firmware:** 11.8.77.3664 (latest)
**Intel ME Driver:** 1950.14.0.1370 (latest)

I started the process today by installing the latest BIOS and firmware for this NUC model, rebooting it, entering the Intel MEBx menu by pressing CTRL+P and changing the default password `admin` to a different one. Next, I enabled the networking feature and restarted the NUC again.

The Intel Management and Security Status software shows that Intel AMT is "Enabled", that the Connection Status is "Connected" and that the Intel ME is "Configured" with Control Mode "Admin". I am also able to visit and log into the default Intel AMT website at `localhost:16992` using the password I set up in Intel MEBx earlier.

The problem I'm facing right now is that when I try to flash the MeshCommander website onto Intel AMT using the latest Firmware Loader (irrespective of whether I choose the Standard or Advanced version), the upload fails with the error message "The remote server returned an error: (500) Internal Server Error."

When I first encountered this error, I downloaded `meshcmd.exe` and tried flashing the website by using the `AmtLoadWebApp` command instead, but the upload also fails that way with the error message "Error, check that computer is powered on." The computer is definitely turned on since I'm running both programs from the NUC itself.

Please let me know if you need any additional info in order to troubleshoot this issue.

**Comment by jsastriawan** [comment]
Potential the size of MeshCommander firmware edition is larger than available space. It may need a fat trimming again.

**Comment by whalehub** [comment]
@jsastriawan I'm not sure if this is what you were talking about, but I've found [terser](https://github.com/terser/terser) with its `--mangle` and `--compress` options to be quite effective in cutting down the size of JavaScript-heavy sites in the past.

**Comment by jsastriawan** [comment]
Aaron, MeshCommander firmware edition is minimized and compressed version of MeshCommander. Ylian's website compiler is the tool to generate this. In the last 5 development iterations, few fetures are added. Thus it may make the code size slightly increased. Some features may need to be removed for this version to maintain small size (< 115K) within FW storage limit.

**Comment by whalehub** [comment]
@jsastriawan @Ylianst Is there anything I can do to help make this happen?

**Comment by whalehub** [comment]
@jsastriawan @Ylianst I'm sadly still getting this error using the latest version of the MeshCommander Firmware Loader (v0.8.8).

**Comment by Ylianst** [comment]
There is an version of Intel AMT firmware that will always return 500 error when trying to upload MeshCommander in firmware. This is not related to size or anything else. As soon as a new version of the BIOS is available, update the platform and it should fix it.

**Comment by whalehub** [comment]
@Ylianst Thanks for the info! Is there somewhere I can sign up to get notified once a new BIOS version is available for NUC7i7DNHE or is there maybe an ETA for when the next update for it is scheduled to be released?

**Comment by whalehub** [comment]
@Ylianst Thanks for the pointer! I searched around the web and eventually found an updated firmware version for this NUC model on a 3rd party site. After upgrading the firmware manually, I was able to upload MeshCommander to Intel AMT successfully. 🚀

**Comment by SavvyChimp** [comment]
@whalehub I have a NUC7i7DNHE with the latest BIOS (0069) and I am getting the same error trying to loading MeshCommander 0.8.8. Any chance you can send me the URL for that updated firmware on the 3rd party site? I would really appreciate it.

**Comment by whalehub** [comment]
@SavvyChimp I downloaded the latest firmware from this site: https://www.win-raid.com/t596f39-Intel-Management-Engine-Drivers-Firmware-amp-System-Tools.html

The GitHub repository which contains the instructions I followed to install the firmware seems to have been deleted a few days ago, but I found a cached version on Google: https://webcache.googleusercontent.com/search?q=cache:oOTj16yZ2CcJ:https://github.com/CHEF-KOCH/HowTo-flash-Intel-Management-Engine-ME-firmware+&cd=3&hl=en&ct=clnk&gl=de

**Comment by SavvyChimp** [comment]
Thanks @whalehub really appreciate the info.

**Comment by sxc731** [comment]
Hi there, how does one figure out if one's AMT firmware is causing this "Error, check that computer is powered on." issue?  I have a fairly recent Comet Lake fanless PC that's exhibiting very much the same issue with MeshCmd v0.7.47.  Here's some details
```
$ sudo ./meshcmd AmtInfo
Intel AMT v14.0.33, activated in Admin Control Mode (ACM).
Wired Enabled, DHCP, XX:YY:ZZ:AA:BB:CC, 192.168.188.143
Connection Status: Direct, CIRA: Disconnected.
$ sudo ./meshcmd AmtStorageState --password xxxxx
Storage State: {
  "information": {
    "version": 1.1,
    "realms": 16252927,
    "user": "xxxxxxx"
  },
  "content": []
}
$ sudo ./meshcmd AmtLoadWebApp --password xxxxx
Uploading MeshCommander...
Error, check that computer is powered on.
```
Many thanks!
