### ISSUE TITLE
MeshCommander Windows Program not showing Remote Desktop as an Option

### ISSUE THREAD

**Issue by CeejayFulmar** [Ylianst/MeshCommander#34]
Hey,

Started to try out your MeshCommander program and so far it looks great.
However, I have noticed on the left hand side, I don't have a remote desktop option. Perhaps a setting wasn't enabled in the initial set up. Perhaps you could advise on how to rectify this?

If you need them:
Running MeshCommander 0.8.8
End-User Machine is Intel ME v11.21.51

Lemme know if you need any other info to help out with this.

Thanks in advance.
Ceejay

**Comment by jsastriawan** [comment]
What is the end-user machine you are managing here? Let me know the CPU and Chipset model or at least the brand and model of the devices. 

Desktop is only available on AMT. It is not available on Intel Standard Manageability. Standard manageability has the same API however it does not have certain features such as Desktop KVM.

**Comment by CeejayFulmar** [comment]
Thanks for getting back so quickly. It is a HP Z8 G4 with 2 x Xeon Silver 4114 
I was under the impression that this system had full vPro but I may be incorrect

**Comment by jsastriawan** [comment]
I see. It has discrete graphic. Discrete graphic is not supported by AMT KVM. This is also a workstation product and it has different version of firmware which is slightly different to normal business PC firmware. Anyway you still can access Serial Over Lan I believe. I hope this clarify.

**Comment by CeejayFulmar** [comment]
Ahh okay - that does make sense. 

Thank you for clarifying for me
