### ISSUE TITLE
No KVM feature availble

### ISSUE THREAD

**Issue by Egorkat** [Ylianst/MeshCommander#48]
I'm trying to use KVM feature from a ECS Q470H6-M6 motherboard with i5-10500 CPU via MeshCommaner 0.9.0 with no success.

I can connect to the system and check Active Features, but there is no KVM listed.
If I try to connect to Desktop I get: "The device indicates that this type of connection is not supported"
Is it a clear sign that MB's firmware is missing this feature or I can somehow troubleshoot this further?

Thanks in advance!

**Comment by jsastriawan** [comment]
There are several potential cause. Most common issue is that you may have discrete graphic on the system. KVM will not work if discrete graphic is added to the system. AMT doesn't know how to talk to non Intel integrated graphic for KVM.

**Comment by Egorkat** [comment]
I'm using built-in GPU from the processor, shouldn't be an issue.

**Comment by Egorkat** [comment]
Funny that initially I started with i5-10400 CPU and had exactly same issues, then realized that it doesn't support vPro and took 10500 one. But issue looks exactly the same...
Can the absence of some SATA storage lead to this?

**Comment by Egorkat** [comment]
Issue was resolved via ME reset, now everything is working as expected.
Turns out that after CPU change AMT engine needs to be reset.
