### ISSUE TITLE
Is it possible to set AMT to activate network interface via the setup.bin file?

### ISSUE THREAD

**Issue by aztlanla** [Ylianst/MeshCommander#49]
I got the setup.bin file configured and tested it out on a host and it doesn't activate the network interface.
Is this something we configure in the setup.bin file? I don't see a variable to configure that in the MeshCommander setup.bin manager.

Thanks

**Comment by rgl** [comment]
I'm successfully using DHCP in my [Setup.bin](https://github.com/rgl/intel-amt-notes/blob/master/Setup.bin) created as described at https://github.com/rgl/intel-amt-notes.
