### ISSUE TITLE
error 400 when enabling vnc

### ISSUE THREAD

**Issue by jassinm** [Ylianst/MeshCommander#56]
I would like to enable vnc 

and set in remove desktop : Port 5900 to Enabled, Legacy KVM viewers and added a 8 chars password.

Unfortunately I get Error 400, unable to set values.

Any idea? tx

**Comment by jsastriawan** [comment]
Would you care to explain the AMT version? At least CPU series will be ok to help identifying the AMT version.

**Comment by jassinm** [comment]
Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz

**Comment by jassinm** [comment]
the "RFB Password" has to be exactly 8 characters, and include at least one each of the following:
- A capital letter
- A number
- A special character (i.e. @,'| etc.)
