### ISSUE TITLE
Can only connect using RLE 8 / RAW8

### ISSUE THREAD

**Issue by jassinm** [Ylianst/MeshCommander#57]
Connection fails when using another encoding then RL8/RAW8. It then keeps on continuously connecting/disconnecting.

Running AMT 11.8.65 on a Intel® Core™ i5-7500T CPU @ 2.70GHz

**Comment by jsastriawan** [comment]
High resolution may only work with lower bit per pixel setting. Please try reducing resolution to  1K/HD.

**Comment by jassinm** [comment]
works at 2560x1440 but fails @ 3840x2160. Thanks
